export const cards = [
  {
    id: 1,
    title: 'AI Artists',
    desc: 'Add talent to AI',
    stageName: 'Contestant 1',
    img: 'https://images.pexels.com/photos/7532110/pexels-photo-7532110.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  },
  {
    id: 2,
    title: 'Logo Design',
    desc: 'Build yor brand',
    stageName: 'Contestant 2',
    img: 'https://images.pexels.com/photos/11295165/pexels-photo-11295165.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  },
  {
    id: 3,
    title: 'WordPress',
    desc: 'Customize your site',
    stageName: 'Contestant 3',
    img: 'https://images.pexels.com/photos/4371669/pexels-photo-4371669.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  },
  {
    id: 4,
    title: 'Voice Over',
    desc: 'Share your message',
    stageName: 'Contestant 4',
    img: 'https://images.pexels.com/photos/7608079/pexels-photo-7608079.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  },
  {
    id: 5,
    title: 'Video Explainer',
    desc: 'Engage your audience',
    stageName: 'Contestant 5',
    img: 'https://images.pexels.com/photos/13388047/pexels-photo-13388047.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  },
  {
    id: 6,
    title: 'Social Media',
    desc: 'Reach more customers',
    stageName: 'Contestant 6',
    img: 'https://images.pexels.com/photos/11378899/pexels-photo-11378899.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  },
  {
    id: 7,
    title: 'SEO',
    desc: 'Unlock growth online',
    stageName: 'Contestant 7',
    img: 'https://images.pexels.com/photos/4820241/pexels-photo-4820241.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  },
  {
    id: 8,
    title: 'Illustration',
    desc: 'Color you dreams',
    stageName: 'Contestant 8',
    img: 'https://images.pexels.com/photos/15032623/pexels-photo-15032623.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load',
  },
];
